### ISSUE TITLE
assert! vs panic! vs env::panic 

### ISSUE THREAD

**Issue by potatodepaulo** [near/near-sdk-rs#190] opened 2020-06-17 01:45 UTC
Asked by someone trying to implement a Rust contract:

> I see that we have multiple ways of panicking or reverting a transaction. What's the best one to use? I've noticed that `env::panic`'s output looks better than that of `assert!` and `panic!`. When I say "it looks better" is because the last 2 have outputted different characters than `env::panic` but not sure if this is relevant to Near by any means. I know `assert!` actually has a different usage on the code overall so maybe let's focus on `env::panic` and `panic!`

Example: 
 ```
 Error: { Error: Smart contract panicked: panicked at 'required 37500000000000000000000 on deposit but sent 0', src/token.rs:205:7
 ```
 this is from `assert!`
 while `env::panic` outputs normally.

CC @mikedotexe

**Comment by potatodepaulo** [comment] 2020-06-17 01:47
Expected behavior: `assert!` and `panic!` should output the same error message.

**Comment by ilblackdragon** [comment] 2020-08-25 11:58
#214 is duplicate of this issue.

**Comment by austinabell** [comment] 2021-09-16 13:47
There was `require!` added in #493 which makes the error messages consistent and not tied to Rust internals which replaces the need for `assert!`. 

As for `panic!` equivalent, I'm hesitant to add to public API because it ties usage very close with `std::fmt` internals we already want to move away from. Is there a large demand to have consistent errors using a similar fmt pattern to `panic!` or can this be considered closed? We already nudge away from using `panic!` in the new SDK docs

**Comment by austinabell** [comment] 2022-09-19 12:38
This issue doesn't seem actionable, going to close. Re-open if you think otherwise

**Closed by austinabell** 2022-09-19 12:38 UTC
Labels: bug, T-dev-tools
