### ISSUE TITLE
Why can't I deploy 2 contracts programmatically

### ISSUE THREAD

**Issue by lilses** [near/near-sdk-rs#637] opened 2021-11-20 19:19 UTC
It seems there arent limits on how many contracts I can deploy based on gas restrictions.

2 wasm files of 100k fail to be deployed programmatically using `promises`.

**Comment by evergreen-trading-systems** [comment] 2021-11-20 19:21
I get this `had 300000000000000 of attached gas but used 2427981370218 of gas` but doesn't make sense

**Comment by evergreen-trading-systems** [comment] 2021-11-20 19:43
I am observing strange behaviour.

1. If I call a contract from CLI and attach max gas of 300000000000000
2. If I call a promise and attach gas of 200000000000000 - works
3. If I call a promise and attach gas of 290000000000000 - it doesn't work

It seems the initial gas supplied from CLI slowly gets decreased through cross-contract functions and we have no way of knowing by how much it is reducing.

**Comment by bowenwang1996** [comment] 2021-11-22 22:35
Yes the issue is if you attach too much gas to the cross contract call, it will fail due to the gas consumed in the current function call. For example, if the you attach 300Tgas to the transaction and spend 20Tgas in the first function call and attempt to attach 290Tgas to the promise, then it will fail because 290 + 20 > 300

**Comment by evergreen-trading-systems** [comment] 2021-11-23 17:24
is there any way to see how much gas remains during cross contracts?

**Comment by bowenwang1996** [comment] 2021-11-24 01:09
You can see the breakdown by querying the transaction through rpc

**Comment by austinabell** [comment] 2022-09-19 15:56
Closing because nothing seems directly actionable. Re-open if there is something, but likely this will be transferred to another repo (SDK doesn't handle these interfaces)

**Closed by austinabell** 2022-09-19 15:56 UTC
Labels: T-dev-tools
