### ISSUE TITLE
Untangle dependencies between nearcore and near-sdk (-sim)

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#372] opened 2021-04-21 14:16 UTC
My understanding is that there's a bunch of accidental complexity around the interactions between near-core and near-sdk-rs code basses. Specifically, I see the following pains:

*   code organization in the near-core depends on near-sdk needs (primitives / primitives-core split)
*   changes to nearcore can break simulator implementation
*   changes to nearcore can break sdk public APIs
*   nearcore needs to think about publishing and versioning crates
*   contracts pull in a lot of dependencies from nearcore (we complile near_vm_logic to wasm only to have the liker dead-code-eliminate it)
*   overall, coordination between core and sdk is required, which slow down development of both.
*   overall, core and sdk have opposing goals: sdk has to provide stable API for our users to confidently build on, core wants to have nimble and cheap to change code.

I see the following fundamental "points of coupling" between the core and the sdk:

*   types used by WASM contracts at runtime (example: core contract uses <span class="error">[PublicKey]</span>([https://github.com/near/core-contracts/blob/39e029619041b564ec08d33a8d65325b653b121b/staking-pool/src/lib.rs#L9](https://github.com/near/core-contracts/blob/39e029619041b564ec08d33a8d65325b653b121b/staking-pool/src/lib.rs#L9)) defined in near-vm-logic)
*   vm logic used by `MockedBlockchain` for "unit-tests" inside the contract itself (<span class="error">[example]</span>([https://github.com/near/near-sdk-rs/blob/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk/src/environment/mocked_blockchain.rs#L16](https://github.com/near/near-sdk-rs/blob/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk/src/environment/mocked_blockchain.rs#L16)))
*   runtime logic used by the simulator (<span class="error">[example]</span>([https://github.com/near/near-sdk-rs/blob/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk-sim/src/runtime.rs#L24](https://github.com/near/near-sdk-rs/blob/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk-sim/src/runtime.rs#L24)))

Here's what I think the dependencies should look like.

For the ***first category***, I think it's reasonable to require that sdk just never uses any types from core. Almost all types are just type-defs at the moment, re-defining them shouldn't be problematic. re-definition would allow us to evolve types flexibly. 

For example, the sdk has a public <span class="error">[`ValidAccountId`]</span>([https://docs.rs/near-sdk/3.1.0/near_sdk/json_types/struct.ValidAccountId.html](https://docs.rs/near-sdk/3.1.0/near_sdk/json_types/struct.ValidAccountId.html)) type and an <span class="error">[`AccountId`]</span>([https://docs.rs/near-sdk/3.1.0/near_sdk/type.AccountId.html](https://docs.rs/near-sdk/3.1.0/near_sdk/type.AccountId.html)) which is just a `String`. This is very wrong from Rust API design perspective, there should be only `pub struct AccountId(String)` which is valid by construction. Refactoring to this representation is very difficult in the current world, as AccountId is shared by internal core core and SDK public API.

I can imagine that, in the future, we might want to introduce a tiny `near-shared-types` crate which encapsulates various validity rules, but we should do that only after we make sure that the API is good.

The ***second category*** is the most problematic imo, contracts depending on near-vm-logic feels very wrong. At the same time, it is essential at this point to write `#<span class="error">[test]</span>` unit tests, and those need access to host function implementations. I think an ideal end-state here would look like this:

*   any nearcore dependencies of near-sdk should be gated by `<span class="error">[target.'cfg(not(target_arch = "wasm32"))'.dependencies]</span>` in ***Cargo.toml***. That way, we ensure that at runtime contracts do not carry nearcore code.
*   in nearcore, we add a new `near-sdk-mock-runtime` crate, and that's the single nearcore crate the SDK is allowed to depend on. This crates re-exports all the APIs required by sdk tests. Narrowing the interface to a single crate makes it clear for nearcore developers which changes could break the sdk.
*   near-sdk never publicly re-exports `near-sdk-mock-runtime` types, even for tests. In contrast, today some tests create a <span class="error">[VMContext by hand]</span>([https://github.com/near/near-sdk-rs/blob/4e880219cce1d2e1c2ad6f685f8ba06e8916aaac/examples/lockable-fungible-token/src/lib.rs#L275-L295](https://github.com/near/near-sdk-rs/blob/4e880219cce1d2e1c2ad6f685f8ba06e8916aaac/examples/lockable-fungible-token/src/lib.rs#L275-L295)). This feels very wrong, as that's a pretty bad API for end-users.

We can use a similar approach for the ***third category***. `near-sdk-sim` is allowed to depend only on one nearcore crate. We can call it `near-sdk-sim-impl`. The simulator is forbidden from directly exposing types from this nearcore crate. All simulation logic is implemented in nearcore, while the sdk exposes it with nice DSLy API. 

The core idea here is that SDK crates have a stable API and **privately** depend on bridging nearcore crates without stability guarantees. So, `near-sdk-sim 4.0.4` will depend on `near-sdk-sim-impl 0.666.0`. We will be free to change the API and impl of the `near-sdk-sim-impl` at a whim, and we can always publish a new version, without thinking about backwards compatability by always incrementing the version. So a minor upgrade of `near-sdk-sim` `4.0.4 -> 4.0.5` can freely major upgrade its internal dependency on `near-sdk-sim-impl` `0.666.0 -> 0.777.0`. Note that `near-sdk-sim-impl` internally can depend on whatever other crates from nearcore it wants. It doesn't have public compatibility obligations, so it can publish the whole jungle without too much problems. 

EDIT: another property of such crate split is that for tests (simulation or unit) user-facing API is maintained in the sdk repo, while the implementation is maintained in the core repo.

I think a specific action item list here would be:

For the sdk:

*   #369 (and easy way to remove one crate from considreatin)
*   Hide `near-vm-logic = "=4.0.0-pre.1"` in sdk Cargo.toml behind a `cfg(not(target_arch = "wasm32"))`
*   Replace re-exports in near-sdk from near-primitives-core with re-definitons
*   Remove `near-primitives-core = "=0.4.0"` from sdk's `Cargo.toml`
*   Remove test-related re-exports of `near-vm-logic`, introduce `near-sdk-mock-runtime` in nearcore

For the simulator 

*   In this crate, separate actual simulation logic and simulators public API into different modules
*   move the logic into a separate crate in the sdk repo, making sure that only this crate depends on nearcore
*   move this crate to nearcore

Whew, that was a lot to type! WDYT?

**Comment by ailisp** [comment] 2021-04-21 17:50
Nice post that summarize the long time pain of sync work of sdk and core. I have some additional thoughts on solving above three category problem.

For first category: I think Willem intended to solve it by move as much as primitive types to near core primitives crate:
https://crates.io/crates/near-primitives-core
https://crates.io/crates/near-primitives

It is possibly better we continues maintain and publish it, and make both nearcore runtime and sdk depends on these two small crates for types

**Comment by ailisp** [comment] 2021-04-21 18:02
> in nearcore, we add a new near-sdk-mock-runtime crate, and that's the single nearcore crate the SDK is allowed to depend on. This crates re-exports all the APIs required by sdk tests. Narrowing the interface to a single crate makes it clear for nearcore developers which changes could break the sdk.

> We can use a similar approach for the third category. near-sdk-sim is allowed to depend only on one nearcore crate. We can call it near-sdk-sim-impl. The simulator is forbidden from directly exposing types from this nearcore crate. All simulation logic is implemented in nearcore, while the sdk exposes it with nice DSLy API.

These two are both solid solution! near-sdk-mock-runtime and 
near-sdk-sim-impl looks have confliction in their dependence on nearcore crates. And does near-sdk-mock-runtime stable API?

**Comment by ailisp** [comment] 2021-04-21 18:11
> near-sdk never publicly re-exports near-sdk-mock-runtime types, even for tests. In contrast, today some tests create a VMContext by hand. This feels very wrong, as that's a pretty bad API for end-users.

I agree. And the example you list is a unit test, while we had vmcontext to bootstrap and we don't need, at the same time we lack ability to pass in vmcontext in simulation test to reproduce testnet txn. I think
- for unit test user should not required to construct a vmcontext, instead they can get a default context, and tweak sender, attached_gas, etc with a DSLy API like you said
- for simulation test you can either hand in a vm context dumped from testnet, or act on the default vm context, modified with the same DSLy API

**Comment by matklad** [comment] 2021-04-22 15:43
>It is possibly better we continues maintain and publish it, and make both nearcore runtime and sdk depends on these two small crates for types

This is probably the most contentious point of the outlined designed. I might be missing something, but to me it seems that there's no actual benefits in sharing the primitives core crate between sdk and nearcore. This is based on two observations.

* the only thing that really binds sdk and core together is contract ABI [sys.rs](https://github.com/near/near-sdk-rs/blob/97fc632fcc58eb7ff7faad0be54ea8ec91dbf694/near-sdk-macros/res/sys.rs). It is based on primitive types, and doesn't require sharing (as evidenced by sys.rs file being in this repository, and not in the nearcore)
* types in primitives-core fall into two categories: those that make zero sense for contracts (ProfileData) and trivial type defs (PublicKey)

I feel it better to completely separate them, and start sharing code if we find a lot of duplicated logic, rather than go in the opposite direction and start from the assumption that sharing is essential. 

(more generally, wrong abstraction is costlier than missing abstraction. It's easier to factor out common code, then to disentangle existing dependencies)

**Comment by matklad** [comment] 2021-04-22 15:48
>And does near-sdk-mock-runtime stable API?

No. Only sdk will depend on this crate, and it will be encapsulated within the sdk. So, if we break `near-sdk-mock-runtime`, we fix one other crate, the sdk. The public API of the sdk stays unchanged. This is in contrast to today's situation, where a change to, eg, near-vm-logic (for example, switch from `pub type PublicKey = Vec<u8>;` to `pub type PublicKey = Box<[u8]>;`) would break contracts.

**Comment by willemneal** [comment] 2021-04-23 16:15
@matklad Thanks for digging into this.  I agree with your action items. 

> for simulation test you can either hand in a vm context dumped from testnet, or act on the default vm context, modified with the same DSLy API

The simulation test API should handle setting up the state and genesis config, block generation, and transaction processing.

[Here is the beginnings of the bindings of sdk-sim to Node.js:](https://github.com/near/near-sdk-as/pull/513/files#diff-b82a948b07c78b85ddbaa2da99d03aecc612ff11e939d4576d630997e97f466a).  However, it would be better to rely on the single nearcore crate as you propose so that the higher level API's are handled by JS, again helping to stabilize the APIs.

**Comment by austinabell** [comment] 2022-09-16 09:36
Closing: no nearcore deps for wasm32-u-u, unit tests nearcore API surface has been minimized as much as possible for now, and sim removed

Optionally can re-open if we want to track being _completely_ separated from nearcore for the public APIs

**Closed by austinabell** 2022-09-16 09:36 UTC
Labels: T-dev-tools
